site_name: ai-router
repo_url: https://github.com/MSAdministrator/ai-router
site_url: https://MSAdministrator.github.io/ai-router
site_description: ai-router is a python cli tool to route local models based on your local system specifications.
site_author: MSAdministrator
edit_uri: edit/main/docs/
repo_name: MSAdministrator/ai-router
copyright: Maintained by <a href="https://github.com/MSAdministrator">MSAdministrator</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/airouter"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MSAdministrator/ai-router
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ai-router

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
