name: release-main

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          release-type: python

      - name: Check out
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        if: ${{ steps.release.outputs.releases_created }}

      - name: Download updated pyproject.toml
        uses: actions/download-artifact@v4
        with:
          name: pyproject-toml
        if: ${{ steps.release.outputs.releases_created }}

      - name: Build package
        run: uv build
        if: ${{ steps.release.outputs.releases_created }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ steps.release.outputs.releases_created }}

  deploy-docs:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
