name: release-main

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          release-type: python

      - name: Check out
        uses: actions/checkout@v7
        if: ${{ steps.release.outputs.releases_created }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        if: ${{ steps.release.outputs.releases_created }}

      - name: Download updated pyproject.toml
        uses: actions/download-artifact@v8
        with:
          name: pyproject-toml
        if: ${{ steps.release.outputs.releases_created }}

      - name: Build package
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  deploy-docs:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Deploy documentation
        run: uv run --extra dev mkdocs gh-deploy --force
